FROM node:18

WORKDIR /app

# copy root package.json (important because dependencies are there)
COPY package*.json ./
RUN npm install

# copy service code
COPY . .

EXPOSE 4000

CMD ["node", "app.js"]