# Payment Service Dockerfile
FROM node:18-alpine

WORKDIR /app

COPY backend/payment-service/package*.json ./
RUN npm install

COPY backend/payment-service ./
COPY shared ./shared

EXPOSE 3002

CMD ["node", "app.js"]