FROM node:18-alpine

WORKDIR /app

# Copy shared directory
COPY shared ./shared

# Copy service
COPY backend/order-service ./

# Install dependencies
RUN npm install

EXPOSE 3001

CMD ["node", "app.js"]
