FROM node:18

WORKDIR /app

# Copy shared directory first
COPY shared /app/shared

# Copy service files
COPY backend/order-service .

# Install dependencies (from service root)
RUN npm install


EXPOSE 3001

CMD ["node", "app.js"]